### ISSUE TITLE
issue with nearest_neighbor_tanimoto.py 

### ISSUE THREAD

**Issue by matany58** [swansonk14/chem_utils#1]
I received the error:   from sklearn.utils.fixes import sparse_lsqr
ImportError: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' while using  nearest_neighbor_tanimoto.py 

Please can it be resolved?

Thanks

**Comment by swansonk14** [comment]
Hi @matany58,

I'm sorry for not seeing your issue before! Are you still having this error? My best guess is that it might be an sklearn version issue. What versions of Python and sklearn are you using?

Thanks,
Kyle
